# Generated by Django 5.2 on 2025-04-16 08:28

import geoposition.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='position',
            field=geoposition.fields.GeopositionField(default='0, 0', max_length=42),
        ),
        migrations.DeleteModel(
            name='GeoPosition',
        ),
    ]
